# Generated by Django 4.0.4 on 2022-05-12 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_rename_curso_curso2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso2',
            new_name='Curso',
        ),
    ]
